---
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  # kubectl create namespace my-namespace
  namespace: my-namespace
type: Opaque
data:
  # base64 encoded values
  PASSWORD: cGFzc3dvcmQx