---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-volume
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  storageClassName: manual
  hostPath:
    path: "/workspace/Devops04/tmp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi